### ISSUE TITLE
[Race/Bug] Two minute wait-time not enforced?

### ISSUE THREAD

**Issue by xnaas** [Redjumpman/Jumper-Plugins#107]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name: race
Version: 1.1.03

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:**
`[p]race start`

**Expected result:**
From `[p]help race start`:
> Must wait 2 minutes after every race to start a new one.

This does not appear to be the case. Users are able to start a race immediately after it's over, preventing other users from claiming their reward.

**Steps to reproduce:**
1. Start a race
2. Finish the race
3. Start another race immediately

**Please tell me about your environment/OS:**
- Windows 10 Pro (64-bit)
- Latest version of Red from `develop` branch

**Comment by Redjumpman** [comment]
🤦‍♂️ I totally forgot to revert that back after testing.... Good catch.

**Comment by Redjumpman** [comment]
Actually, I may need some more information on this. The command for race start should be set to once, per 120 seconds, per server.

**Comment by Redjumpman** [comment]
If you reload the cog, if you start a race, and reset the cog, then this cooldown will be reset.

**Comment by xnaas** [comment]
This still happens, no matter what. There delay doesn't appear to be enforced. Is there anything you'd like me to try/test?

**Comment by Redjumpman** [comment]
I don't have anything for you to try atm, still working on it and some other issues. Should have a fix for it soon.

**Comment by xnaas** [comment]
Alright, sounds good. 😄

**Comment by Redjumpman** [comment]
Just to clarify your issue: Users on the same server, are able to use this command more than once per 120 seconds. For example:

User A: Race Start
User B: Race Start

**Comment by xnaas** [comment]
Hmm, maybe I misunderstand.

Events:

1. Start race
2. users join and it starts after 90 second (I've set it to 90)
3. Race ends
4. Someone can start a new race **immediately** and can stop someone from collecting their reward

I guess that's expected behavior, since 90 seconds + ~30 seconds of race = ~120 seconds. I thought it was 120 seconds _after_ the race ended.

FWIW, everyone using it says "why don't I just get my reward? why do I have to claim?" but I love telling them to suck it up. 😜

**Comment by Redjumpman** [comment]
No I have a hard-coded cooldown of 120 seconds on the command. This is to prevent people from spamming start race over and over and then complaining to me that their bot died. As you can tell from this issue, it can be hard for me to discern what is happening on their bot when everything works as intended for me. 

One of the reasons I made it a 'claim' is because users enter a game for credits without even having a bank account 🙄. Economy in RedV2 is really annoying to handle when someone doesn't have an account. I can see how that is inconvenient for the players though. I would have to strip out some stuff to make that work and figure out how to handle that gracefully at the end of the race. Let me think about this, because I have a policy of not adding new features to my Red v2 plugins, however this is somewhat of a grey area. For a temporary fix, if you open up the code find this line 

```Python
@commands.cooldown(1, 120, commands.BucketType.server)
```
Change 120 to the number of seconds you would like to wait. In your case you might want to make it 240. I hope this helps.

**Comment by xnaas** [comment]
I'll give that a try after Blank Panther.

Thanks!

**Comment by xnaas** [comment]
Yup, upping it to 240 worked quite well. 👏 I'll probably play around with a number that works best for us, but I really appreciate the support. :D 

>One of the reasons I made it a 'claim' is because users enter a game for credits without even having a bank account 🙄. Economy in RedV2 is really annoying to handle when someone doesn't have an account. I can see how that is inconvenient for the players though. I would have to strip out some stuff to make that work and figure out how to handle that gracefully at the end of the race. Let me think about this, because I have a policy of not adding new features to my Red v2 plugins, however this is somewhat of a grey area.

You don't have to worry about it. I know V3 is Soon™, that's fine. 👍
