### ISSUE TITLE
[Shop] Edit item shop order after creation

### ISSUE THREAD

**Issue by Zylvian** [Redjumpman/Jumper-Plugins#130]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Shop
Version: 3.0.07

# Feature Description
At the moment, in order to edit the position of which items are displayed in a shop, one has to delete every item before it.
I suggest that instead of being sorted by it's mongodb order, the item is assigned an ID which can later be edited, and the sorting is based on ID. If another item has the same ID, they swap id. OR it pushes all items with a higher ID one value up(best).

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:**

**Expected result:**

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by Redjumpman** [comment]
Eh. Adding yet another field is going to just further muddy the complexity of this cog. I'll look at adding some sorting methods individually to the shops. Like instead of editing an item id, you can just change how each particular shop sorts their items. So maybe you can use "Price, alphabetical, quantity, type" something like that.

**Comment by Redjumpman** [comment]
Added shop sorting as of Shop 3.1 #152
