### ISSUE TITLE
[Race/Feature Request] - Leaderboard

### ISSUE THREAD

**Issue by AbdouPuddin** [Redjumpman/Jumper-Plugins#87]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  race
Version: race version 1.1.02

# Feature Description
*Please include the motivation / use case for this feature.*
People need a reason to play in race, so they need to have a leaderboard and a rank!
So if you add server leaderboard and global one for credits and rank and profile commands that would be more awesome for people to play it, and that make it more exciting, and why not adding those   ;)
# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:**

**Expected result:**

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by Mamalus** [comment]
I really don’t see any use for profiling and credits ranking and leaderboard. This sounds more like a leveler cog.

**Comment by AbdouPuddin** [comment]
And i don't see what's the point of playing in a race without getting anything

**Comment by skeith** [comment]
Instead of leaderboard, I'd prefer Stats like Heist

**Comment by Mamalus** [comment]
What’s Keith said  sounds more appropriate. Stats as a general rule wins and lost ratio. For profile I’m confused about that since I end up thinking about Stevy’s cog

**Comment by Redjumpman** [comment]
Do you mean to have a leaderboard that ranks players based on the number of wins in races? One problem That I see with this, is the fact that you can race against the bot several times while someone else isn't even online. While it brings me a lot of joy to know that someone would attempt to go so far in a simple game I made, it's not a lot of fun for others at that point. 

I think maybe if there was a grand prix that could be hosted at a specific time (Set by the server admin) it might make it more interesting. However it then becomes a mad dash to see who can fill the slots first on a large server since there is a limit to the racers. I like the ideas, but I think this needs to be fleshed out a bit more.

**Comment by skeith** [comment]
Adding leaderboard will open new issue. There will be people (I guarantee it will) asking for leaderboard reset and reward for being on top of leaderboard per period. This is why I kind of disagree adding such feature.

For race cog, me and @Mamalus did some brainstorming back then and have several ideas. I will make an issue for it when I have the time

**Comment by Redjumpman** [comment]
I may still do this, but for now I am electing to only do stat tracking.
